### ISSUE TITLE
I still get broken packages even with clone

### ISSUE THREAD

**Issue by justsayno** [Microsoft/WingTipTickets#25]
I haven' tried with Github for Windows but I have done it with ssh clone and you get the same corruption issues.

Also then when I open it in VS2015 it says its still associated with PS 2.7 and won't open as a result.

**Comment by meyergm** [comment]
There is one legacy application in the solution. Can you run VS as administrator and see if there is an error? Can you attempt to open the .zip files?

**Comment by justsayno** [comment]
Yep I can open it with Admin and upgrade to 2.9. I am actually working on this as part of some work for Microsoft. Should I do a pull request with fixed packages? Packages are not open-able even when cloned.

**Comment by meyergm** [comment]
The packages work fine when they are downloaded through the GitHub client. I have seen this issue using the command line. Please PM me so I can understand what you are doing with the application.

**Comment by justsayno** [comment]
Didn't Github remove PM a few years back? email me seth.reid@intergen.co.nz
